"Title:","クロッピング設定"
"Number:/cropper/zcrop/near","Z方向クロップ位置:カメラ側"
"Number:/cropper/zcrop/far","床側"
"Number:/cropper/sphare/x","円クロップ:中心X座標"
"Number:/cropper/sphare/y","Y座標"
"Number:/cropper/sphare/z","Z座標"
"Number:/cropper/sphare/r","半径"
"Title:","RANSAC設定"
"Number:/regist_master_model/ransac/fitness_threshold","fitness閾値"
"Number:/regist_master_model/ransac/max_iteration","反復最大数"
"Title:","ICP設定"
"Number:/regist_master_model/icp/fitness_threshold","一致率閾値"
"Number:/regist_master_model/icp/translation_threshold/upper_x","X座標上限"
"Number:/regist_master_model/icp/translation_threshold/lower_x","X座標下限"

